# Generated by Django 5.0.3 on 2024-05-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
            ],
        ),
    ]
