# Generated by Django 6.0.3 on 2026-03-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index_modal',
            new_name='UserProfile',
        ),
    ]
