# Generated by Django 5.0.3 on 2024-04-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='email',
        ),
    ]
