# Generated by Django 5.0.3 on 2024-06-27 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.user_signupform'),
        ),
    ]
