# Generated by Django 5.0.3 on 2024-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp16', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_login',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_signup',
            name='eid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emp_signup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
