# Generated by Django 5.0.3 on 2024-04-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp16', '0002_alter_emp_login_username_alter_emp_signup_eid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_login',
            name='password',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp_login',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp_signup',
            name='eid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp_signup',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emp_signup',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp_signup',
            name='password',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
